#ifndef NUMERICREPLIES_HPP
#define NUMERICREPLIES_HPP

#define ERR_NEEDMOREPARAMS 461
#define ERR_ALREADYREGISTRED 462

#define ERR_PASSWDMISMATCH 464

#define ERR_NONICKNAMEGIVEN 431
#define ERR_ERRONEUSNICKNAME 432
#define ERR_NICKNAMEINUSE 433

#endif
